### ISSUE TITLE
Não Compila (Arduino 1.8.15 Windows 10 Home 21H1)

### ISSUE THREAD

**Issue by petruscl** [pion-labs/pion-educational-kits#1]
Instalei pelo gerenciador de placas com o JSON que tem na raiz do repositório mas não está compilando.

`Arduino: 1.8.15 (Windows 10), Board: "PION Educational CubeSat, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 921600, None"

C:\Users\Petrus\Projetos\Arduino\libraries\ESPAsyncWebServer\src\WebAuthentication.cpp:23:17: fatal error: md5.h: No such file or directory

Multiple libraries were found for "SD.h"

compilation terminated.

 Used: C:\Users\Petrus\AppData\Local\Arduino15\packages\PION Educational Kits\hardware\esp32\1.0.2\libraries\SD

 Not used: C:\Program Files (x86)\Arduino\libraries\SD

 Not used: C:\Users\Petrus\Projetos\Arduino\libraries\SD

Multiple libraries were found for "ESPAsyncWebServer.h"

 Used: C:\Users\Petrus\Projetos\Arduino\libraries\ESPAsyncWebServer

 Not used: C:\Users\Petrus\AppData\Local\Arduino15\packages\PION Educational Kits\hardware\esp32\1.0.2\libraries\ESPAsyncWebServer

Multiple libraries were found for "ArduinoJson.h"

 Used: C:\Users\Petrus\Projetos\Arduino\libraries\ArduinoJson

 Not used: C:\Users\Petrus\AppData\Local\Arduino15\packages\PION Educational Kits\hardware\esp32\1.0.2\libraries\ArduinoJson

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\Petrus\AppData\Local\Arduino15\packages\PION Educational Kits\hardware\esp32\1.0.2\libraries\WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

Multiple libraries were found for "ESPAsyncTCP.h"

 Used: C:\Users\Petrus\Projetos\Arduino\libraries\ESPAsyncTCP

 Not used: C:\Users\Petrus\AppData\Local\Arduino15\packages\PION Educational Kits\hardware\esp32\1.0.2\libraries\ESPAsyncTCP

exit status 1

Error compiling for board PION Educational CubeSat.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by joaopedrovbs** [comment]
Olá @petrusz1, 

Pela sua mensagem de erro entendi que você tem em sua pasta `C:\Users\Petrus\Projetos\Arduino\libraries\` uma outra versão da biblioteca **ESPAsyncWebServer** e que essa foi a versão que foi utilizada para a compilação do código, o que causou o erro. 

Podemos ver também numa linha abaixo que a versão da biblioteca **ESPAsyncWebServer** que enviamos junto com a instalação da placa está como **Not used** (Não utilizada): `C:\Users\Petrus\AppData\Local\Arduino15\packages\PION Educational Kits\hardware\esp32\1.0.2\libraries\ESPAsyncWebServer`, e esse é um erro causado pela forma como a IDE do Arduino prioriza suas instalações de bibliotecas, sendo que nesse caso a sua instalação na pasta `C:\Users\Petrus\Projetos\Arduino\libraries\` foi dada como mais importante e deve ser de uma versão diferente da instalação que disponibilizamos junto com nosso suporte a placa. 

Como o erro é realmente causado pela IDE do Arduino onde não temos controle entendo que a compilação pode ser executada corretamente se por exemplo retirar a pasta  **ESPAsyncWebServer** do local `C:\Users\Petrus\Projetos\Arduino\libraries\` para não confundir o compilador da IDE com qual biblioteca utilizar, é bom notar que há tambem um conflito com a biblioteca **ArduinoJson** mais abaixo, que pode levar ao mesmo problema. 

Portanto, recomendo mover as pastas **ESPAsyncWebServer** e **ArduinoJson** de `C:\Users\Petrus\Projetos\Arduino\libraries\` temporariamente para outra pasta para resolver o problema.

**Comment by petruscl** [comment]
Resolvido, valeu.
