### ISSUE TITLE
'PINK' was not declared in this scope

### ISSUE THREAD

**Issue by sandrosato** [pion-labs/pion-educational-kits#2]
![image](https://user-images.githubusercontent.com/89849040/136021303-674c1b17-4c9f-47aa-a43d-37ecc6c4b654.png)

**Comment by joaopedrovbs** [comment]
Obrigado @sandrosato , na verdade esse exemplo deveria utilizar a cor PURPLE, vinda da união do azul e do vermelho, estamos executando as correções!
