### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

### ISSUE THREAD

**Issue by sandrosato** [pion-labs/pion-educational-kits#3]
O sketch é compilado com sucesso e ao tentar carregar, quando chega na fase
Connecting ........ _____ ..... _____ ..... _____ .... ._____ ..... _____ ..... _____ ..... _____
### Resultado da IDE do Arduino 
Arduino: 1.8.16 (Windows 10), Placa:"PION Educational CubeSat, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 921600, None"
O sketch usa 1055398 bytes (80%) de espaço de armazenamento para programas. O máximo são 1310720 bytes.
Variáveis globais usam 44128 bytes (13%) de memória dinâmica, deixando 283552 bytes para variáveis locais. O máximo são 327680 bytes.
esptool.py v3.0-dev
Serial port COM4
Connecting ........ _____ ..... _____ ..... _____ .... ._____ ..... _____ ..... _____ ..... _____
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

**Comment by joaopedrovbs** [comment]
Olá @sandrosato se seu cabo USB está funcionando em outros dispositivos e nem ele nem a escolha da porta Serial COM(x) forem o problema nesse caso, manda um email pra liftoff@pionlabs.com.br pra que a gente dê o devido suporte e possa realizar alguma troca se o problema detectado for de algo que aconteceu no hardware!

**Comment by sandrosato** [comment]
Obrigado!

**Comment by Natalie9** [comment]
Gostaria de saber como foi a resolução desse problema pois passei pelo mesmo.

**Comment by sandrosato** [comment]
@Natalie9 depois de varias tentativas e testes, tivemos que entrar em contato com  liftoff@pionlabs.com.br para realizar a troca pois não conseguimos resolver o problema.
