### ISSUE TITLE
Corrigir pressãoAtm 

### ISSUE THREAD

**Issue by sandrosato** [pion-labs/pion-educational-kits#4]
Na função float getPressure()
O exemplo de código tem pressãoAtm
Porém o compilador não aceita acentos

**Comment by joaopedrovbs** [comment]
Corrigido @sandrosato, muito obrigado, realmente estava assim na documentação mas correto nos exemplos!

Documentação corrigida:
https://github.com/pion-labs/pion-educational-kits/wiki/Documenta%C3%A7%C3%A3o-do-Software
