### ISSUE TITLE
toggleSD não exite

### ISSUE THREAD

**Issue by sandrosato** [pion-labs/pion-educational-kits#5]
A descrição da função createSDLogTask() faz uma referência para uma função toggleSD() que não existe ou não está documentada.
Não seria activateSDLog() ?
Ou existe a função toggleSD()

**Comment by joaopedrovbs** [comment]
Olá @sandrosato , existe a função toggleSD sim e ela só não está documentada pois é de uso interno, porém activateSDLog() faz a mesma coisa que ela mantendo a idempotência.
