### ISSUE TITLE
error: 'server' was not declared in this scope

### ISSUE THREAD

**Issue by sandrosato** [pion-labs/pion-educational-kits#6]
Nesta parte do código, onde devemos criar o server e como?

// Modificação para servir uma página html
void serverResponse(){
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){

**Comment by PhPires13** [comment]
Também estou tendo esse problema, conseguiu resolver de alguma maneira ?

**Comment by sandrosato** [comment]
Não, mas não precisei usar mais essa função.

**Comment by PhPires13** [comment]
Se puder me mostrar como conseguiu configurar o protocolo HTTP com JSON, agradeceria muito. Não tenho consguido.

**Comment by sandrosato** [comment]
na vdd no meu caso não era preciso ter esse servidor de pagina web, o caminho foi apenas enviar uma solicitação post
primeiro trabalhei com a estrutura json com a biblioteca do https://arduinojson.org/
depois a comunicação usei dicas de como fazer ESP32 HTTP GET and HTTP POST https://randomnerdtutorials.com/esp32-http-get-post-arduino/
E testamos com o Post Test Server V2 https://ptsv2.com/
